<?php

return array(
	'label' => array(
		'en' => array('Centered wrapper start', ''),
		'de' => array('Zentrierter Bereich Anfang', 'Erzeugt einen zentrierten Inhaltsbereich'),
		'fr' => array('Début de zone centrée', 'Crée une zone de contenu centrée'),
	),
	'types' => array('content', 'module'),
	'standardFields' => array('cssID', 'space'),
	'wrapper' => array(
		'type' => 'start',
	),
	'fields' => array(
		array(
			'inputType' => 'group',
			'label' => array(
				'en' => array('Border settings'),
				'de' => array('Rahmeneinstellungen'),
				'fr' => array('Paramètres de bordure'),
			),
		),
		'borderTop' => array(
			'label' => array(
				'en' => array('Border top', 'Creates a line above the element'),
				'de' => array('Rahmen oben', 'Erzeugt vor dem Element eine Linie.'),
                'fr' => array('Bordure haut', 'Crée une ligne au-dessus de l\'élément'),
            ),
			'inputType' => 'checkbox',
			'eval' => array('tl_class' => 'w50'),
		),
		'borderBottom' => array(
			'label' => array(
				'en' => array('Border bottom', 'Creates a line below the element'),
				'de' => array('Rahmen unten', 'Erzeugt nach dem Element eine Linie.'),
                'fr' => array('Bordure du bas', 'Crée une ligne sous l\'élément'),
            ),
			'inputType' => 'checkbox',
			'eval' => array('tl_class' => 'w50'),
		),
		'borderTopColor' => array(
			'label' => array(
				'en' => array('Border color top', 'Leave this field empty to use the default color.'),
				'de' => array('Rahmenfarbe oben', 'Lassen Sie dieses Feld leer um die Standardfarbe zu verwenden.'),
                'fr' => array('Couleur bordure haut', 'Laissez ce champ vide pour utiliser la couleur par défaut.'),
            ),
			'inputType' => 'text',
			'eval' => array(
				'colorpicker' => true,
				'tl_class' => 'w50',
			),
		),
		'borderBottomColor' => array(
			'label' => array(
				'en' => array('Border color bottom', 'Leave this field empty to use the default color.'),
				'de' => array('Rahmenfarbe unten', 'Lassen Sie dieses Feld leer um die Standardfarbe zu verwenden.'),
				'fr' => array('Couleur bordure bas', 'Laissez ce champ vide pour utiliser la couleur par défaut.'),
			),
			'inputType' => 'text',
			'eval' => array(
				'colorpicker' => true,
				'tl_class' => 'w50',
			),
		),
		'borderTopWidth' => array(
			'label' => array(
				'en' => array('Border width top', ''),
				'de' => array('Rahmenbreite oben', 'Lassen Sie dieses Feld leer um die Standardbreite zu verwenden.'),
				'fr' => array('Largeur de la bordure haut', 'Laissez ce champ vide pour utiliser la largeur par défaut.'),
			),
			'inputType' => 'inputUnit',
			'options' => array('px', '%', 'em', 'rem', 'ex', 'pt', 'pc', 'in', 'cm', 'mm'),
			'eval' => array(
				'includeBlankOption' => true,
				'rgxp' => 'digit_auto_inherit',
				'tl_class' => 'w50',
			),
		),
		'borderBottomWidth' => array(
			'label' => array(
				'en' => array('Border width bottom', ''),
				'de' => array('Rahmenbreite unten', 'Lassen Sie dieses Feld leer um die Standardbreite zu verwenden.'),
				'fr' => array('Largeur de la bordure bas', 'Laissez ce champ vide pour utiliser la largeur par défaut.'),
			),
			'inputType' => 'inputUnit',
			'options' => array('px', '%', 'em', 'rem', 'ex', 'pt', 'pc', 'in', 'cm', 'mm'),
			'eval' => array(
				'includeBlankOption' => true,
				'rgxp' => 'digit_auto_inherit',
				'tl_class' => 'w50',
			),
		),
        'outsideMargin' => array(
            'label' => array(
                'fr' => array('Magin', 'Marge personnalisé. Ex: 10px 20px 30px'),
            ),
            'inputType' => 'text',
            'eval' => array(
                'tl_class' => 'w50',
            ),
        ),
        'insidePadding' => array(
            'label' => array(
                'fr' => array('Padding', 'Forcer padding personnalisé. Ex: 10px 20px 30px'),
            ),
            'inputType' => 'text',
            'eval' => array(
                'tl_class' => 'w50',
            ),
        ),
		array(
			'inputType' => 'group',
			'label' => array(
				'en' => array('Background'),
				'de' => array('Hintergrund'),
				'fr' => array('Arrière plan'),
			),
		),
		'backgroundImage' => array(
			'label' => array(
				'en' => array('Background image or video', 'Choose an image and/or multiple video files.'),
				'de' => array('Hintergrundbild oder -Video', 'Wählen Sie ein Bild und/oder mehrere Videodateien aus.'),
                'fr' => array('Image ou vidéo de fond', 'Choisissez une image et/ou plusieurs fichiers vidéo.'),
            ),
			'inputType' => 'fileTree',
			'eval' => array(
				'tl_class' => 'clr',
				'multiple' => true,
				'fieldType' => 'checkbox',
				'filesOnly' => true,
				'extensions' => implode(',', Contao\System::getContainer()->getParameter('contao.image.valid_extensions')) . ',mp4,webm,ogv,ogg',
			),
		),
		'backgroundImageSize' => array(
			'label' => array(
				'en' => array('Image width and height', ''),
				'de' => array('Bildbreite und Bildhöhe', ''),
                'fr' => array('Largeur et hauteur de l\'image', ''),
            ),
			'inputType' => 'imageSize',
			'options' => Contao\System::getContainer()->get('contao.image.sizes')->getAllOptions(),
			'reference' => &$GLOBALS['TL_LANG']['MSC'],
			'eval' => array(
				'rgxp' => 'digit',
				'tl_class' => 'w50',
				'includeBlankOption' => true,
			),
		),
		'backgroundRepeat' => array(
			'label' => array(
				'en' => array('Background repeat', ''),
				'de' => array('Hintergrund wiederholen', ''),
                'fr' => array('Répétition du fond', ''),
            ),
			'inputType' => 'select',
			'options' => array(
				'',
				'repeat',
				'repeat-x',
				'repeat-y',
			),
			'reference' => array(
				'' => array('en' => 'No repeat', 'de' => 'Nicht Wiederholen', 'fr' => 'Ne pas répétez'),
				'repeat' => array('en' => 'Repeat', 'de' => 'Wiederholen', 'fr' => 'Répéter'),
				'repeat-x' => array('en' => 'Repeat-x', 'de' => 'Horizontal Wiederholen', 'fr' => 'Répéter horizontalement'),
				'repeat-y' => array('en' => 'Repeat-y', 'de' => 'Vertikal Wiederholen', 'fr' => 'Répéter verticalement'),
			),
			'eval' => array('tl_class' => 'w50'),
		),
		'backgroundSize' => array(
			'label' => array(
				'en' => array('Background image size', ''),
				'de' => array('Hintergrundbildgröße', ''),
                'fr' => array('Taille de l\'image d\'arrière-plan', ''),
            ),
			'inputType' => 'select',
			'options' => array(
				'',
				'contain',
				'100% 100%',
				'auto auto',
				'cover',
			),
			'reference' => array(
				'' => array('en' => '-', 'de' => '-', 'fr' => '-'),
				'contain' => array('en' => 'Proportional', 'de' => 'Proportional', 'fr' => 'Proportionnel (contain)'),
				'100% 100%' => array('en' => 'Distorted', 'de' => 'Verzerrt', 'fr' => 'Déformé (100% 100%)'),
				'auto auto' => array('en' => 'Original', 'de' => 'Originalgröße', 'fr' => 'Format original (auto auto)'),
				'cover' => array('en' => 'Cover', 'de' => 'Abdeckung (Cover)', 'fr' => 'Couverture (Cover)'),
			),
			'eval' => array('tl_class' => 'w50'),
		),
		'backgroundPosition' => array(
			'label' => array(
				'en' => array('Background position', 'Can\'t be combined with the parallax effect.'),
				'de' => array('Hintergrundposition', 'Nicht mit Parallax-Effekt kombinierbar.'),
				'fr' => array('Position du fond prédéfinie', 'Ne peut pas être combiné avec l\'effet de parallaxe.'),
			),
			'inputType' => 'select',
			'options' => array(
				'',
				'0 0',
				'50% 0',
				'100% 0',
				'0 50%',
				'50% 50%',
				'100% 50%',
				'0 100%',
				'50% 100%',
				'100% 100%',
			),
			'reference' => array(
				'' => array('en' => '-', 'de' => '-', 'fr' => '-'),
				'0 0' => array('en' => 'Left | Top', 'de' => 'Links | Oben', 'fr' => 'Gauche | Haut'),
				'50% 0' => array('en' => 'Center | Top', 'de' => 'Mitte | Oben', 'fr' => 'Centre | Haut'),
				'100% 0' => array('en' => 'Right | Top', 'de' => 'Rechts | Oben', 'fr' => 'Droite | Haut'),
				'0 50%' => array('en' => 'Left | Center', 'de' => 'Links | Mitte', 'fr' => 'Gauche | Centre'),
				'50% 50%' => array('en' => 'Center | Center', 'de' => 'Mitte | Mitte', 'fr' => 'Centre | Centre'),
				'100% 50%' => array('en' => 'Right | Center', 'de' => 'Rechts | Mitte', 'fr' => 'Droite | Centre'),
				'0 100%' => array('en' => 'Left | Bottom', 'de' => 'Links | Unten', 'fr' => 'Gauche | Bas'),
				'50% 100%' => array('en' => 'Center | Bottom', 'de' => 'Mitte | Unten', 'fr' => 'Centre | Bas'),
				'100% 100%' => array('en' => 'Right | Bottom', 'de' => 'Rechts | Unten', 'fr' => 'Droite | Bas'),
			),
			'eval' => array('tl_class' => 'w50'),
		),
        'backgroundPositionCustom' => array(
            'label' => array('Position du fond personnalisée', 'Non compatible avec l\'effet Parallax, surcharge la valeur prédéfinie (Exemple 50% 50%)'),
            'inputType' => 'text',
            'eval' => array(
                'tl_class' => 'w50',
            ),
        ),
        'backgroundWidth' => array(
            'label' => array('Largeur de la zone contenant l\'image', 'Ex: 50%'),
            'inputType' => 'text',
            'eval' => array(
                'tl_class' => 'w50',
            ),
        ),
        'backgroundAbsolutePositionLeft' => array(
            'label' => array('Position absolue gauche contenant l\'image', 'Défaut: 0, Ex: 50%;'),
            'inputType' => 'text',
            'eval' => array(
                'tl_class' => 'w50',
            ),
        ),
        'backgroundAbsolutePositionRight' => array(
            'label' => array('Position absolue droite contenant l\'image', 'Défaut: 0, Ex: 50%;'),
            'inputType' => 'text',
            'eval' => array(
                'tl_class' => 'w50',
            ),
        ),
        'backgroundBlur' => array(
            'label' => array('Flou de l\'image de fond', 'De 0 à X'),
            'inputType' => 'text',
            'eval' => array('tl_class' => 'w50'),
        ),
        'backgroundContrast' => array(
            'label' => array('Contraste de l\'image de fond', 'De 0 à X'),
            'inputType' => 'text',
            'eval' => array('tl_class' => 'w50'),
        ),
        'backgroundBrightness' => array(
            'label' => array('Luminosité de l\'image de fond', 'De 0 à 1 pour foncer et 1 à X pour éclaircir'),
            'inputType' => 'text',
            'eval' => array('tl_class' => 'w50'),
        ),
        'backgroundGrayscale' => array(
            'label' => array('Désaturation de l\'image de fond', 'Exemple: .5 pour 50% De 0 (couleur) à 1 (noir et blanc)'),
            'inputType' => 'text',
            'eval' => array('tl_class' => 'w50'),
        ),
        'backgroundOpacity' => array(
            'label' => array(
                'en' => array('Image opacity'),
                'de' => array('Bildopazität'),
                'fr' => array('Opacité de l\'image', 'Exemple: .2 pour 20% - .2'),
            ),
            'inputType' => 'text',
            'eval' => array('tl_class' => 'w50'),
        ),
		'colorVariation' => array(
			'label' => array(
				'en' => array('Predefined background color', 'Choose one of the predefined colors as background. You can customize the colors using the Theme Assistant, CSS or Sass.'),
				'de' => array('Vordefinierte Hintergrundfarbe', 'Eine der vordefinierten Farben als Hintergrund verwenden. Die Farben lassen sich mit dem Theme Assistant, CSS oder Sass anpassen.'),
                'fr' => array('Couleur de fond prédéfinie', 'Choisissez l\'une des couleurs prédéfinies comme arrière-plan. Vous pouvez personnaliser les couleurs à l\'aide de l\'assistant de thème, CSS ou Sass.'),
            ),
			'inputType' => 'select',
			'options' => array(
				'',
				'-highlight-color',
				'-background-color-1',
				'-background-color-2',
				'-background-color-3',
				'-background-color-4',
			),
			'reference' => array(
				'' => array('en' => 'Transparent', 'de' => 'Transparent', 'fr' => 'Transparent'),
				'-bg-color-white' => array('en' => 'White', 'de' => 'Weiß', 'fr' => 'Blanc'),
				'-highlight-color' => array('en' => 'Highlight color', 'de' => 'Highlight-Farbe', 'fr' => 'Couleur de surbrillance'),
				'-background-color-1' => array('en' => 'Background color 1', 'de' => 'Hintergrundfarbe 1', 'fr' => 'Couleur de fond 1'),
				'-background-color-2' => array('en' => 'Background color 2', 'de' => 'Hintergrundfarbe 2', 'fr' => 'Couleur de fond 2'),
				'-background-color-3' => array('en' => 'Background color 2', 'de' => 'Hintergrundfarbe 3', 'fr' => 'Couleur de fond 3'),
				'-background-color-4' => array('en' => 'Background color 4', 'de' => 'Hintergrundfarbe 4', 'fr' => 'Couleur de fond 4'),
			),
			'eval' => array('tl_class' => 'w50'),
		),
		'backgroundColor' => array(
			'label' => array(
				'en' => array('Custom background color', 'Overwrites the predefined color.'),
				'de' => array('Eigene Hintergrundfarbe', 'Überschreibt die vordefinierte Einstellung.'),
                'fr' => array('Couleur de fond personnalisée', 'Remplace la couleur prédéfinie.'),
            ),
			'inputType' => 'text',
			'eval' => array(
				'colorpicker' => true,
				'tl_class' => 'w50 wizard',
			),
		),
		'backgroundVariation' => array(
			'label' => array(
				'en' => array('Background effect', ''),
				'de' => array('Hintergrundeffekt', ''),
                'fr' => array('Effet de fond', ''),
            ),
			'inputType' => 'select',
			'options' => array(
				'',
				'-background-parallax',
				'-background-mousemove',
				'-background-mousemove-inverted',
			),
			'reference' => array(
				'' => array('en' => '-', 'de' => '-'),
				'-background-parallax' => array('en' => 'Parallax', 'de' => 'Parallax', 'fr' => 'Parallax'),
				'-background-mousemove' => array('en' => 'Move with mouse', 'de' => 'Mit der Maus bewegend', 'fr' => 'Déplacer avec la souris'),
				'-background-mousemove-inverted' => array('en' => 'Move against mouse', 'de' => 'Entgegen der Maus bewegend', 'fr' => 'Déplacer sens inverse de la souris'),
			),
			'eval' => array('tl_class' => 'w50'),
		),
		'backgroundColor2' => array(
			'label' => array(
				'en' => array('Second background color', 'Create a visual edge in the background.'),
				'de' => array('Zweite Hintergrundfarbe', 'Erzeugt eine optische Kante im Hintergrund.'),
                'fr' => array('Deuxième couleur de fond', 'Créez un contour visuel en arrière-plan.'),
            ),
			'inputType' => 'text',
			'eval' => array(
				'colorpicker' => true,
				'tl_class' => 'w50 wizard',
			),
		),
		'backgroundColor2Position' => array(
			'label' => array(
				'en' => array('Second background color position', 'e.g. 50%, 100px, 10em,...'),
				'de' => array('Zweite Hintergrundfarbe Position', 'Z. B. 50%, 100px, 10em,...'),
                'fr' => array('Position de la deuxième couleur de fond', 'e.g. 50%, 100px, 10em,...'),
            ),
			'inputType' => 'text',
			'eval' => array(
				'tl_class' => 'w50',
			),
		),
        'backgroundGradient' => array(
            'label' => array(
                'fr' => array('Ajouter un dégradé sur l\'image', 'Gradient generator <a target="_blank" href="https://cssgradient.io/">cssgradient.io</a> '),
            ),
            'inputType' => 'text',
            'eval' => array('tl_class' => 'w50'),
        ),
		'colorInverted' => array(
			'label' => array(
				'en' => array('Invert text color', 'Use lighter text color for dark backgrounds and images.'),
				'de' => array('Textfarbe invertieren', 'Helle Textfarbe für dunkle Hintergründe und Fotos.'),
                'fr' => array('Inverser la couleur du texte', 'Utilisez une couleur de texte plus claire pour les arrière-plans et les images sombres.'),
            ),
			'inputType' => 'checkbox',
			'eval' => array(
				'tl_class' => 'w50 m12',
			),
		),
		'noBackground' => array(
			'label' => array(
				'en' => array('Remove background on', 'Removes the background image and second background color on smaller screens.'),
				'de' => array('Hintergrund entfernen ab', 'Entfernt Hintergrundbild und die zweite Hintergrundfarbe auf kleineren Bildschirmen.'),
                'fr' => array('Supprimer l\'arrière-plan sur les mobiles', 'Supprime l\'image d\'arrière-plan et la deuxième couleur d\'arrière-plan sur les petits écrans.'),
            ),
			'inputType' => 'select',
			'options' => array(
				'-no-background-mobile',
				'-no-background-tablet',
			),
			'reference' => array(
				'-no-background-mobile' => array('en' => 'Mobile (600 Pixel)', 'de' => 'Mobil (600 Pixel)', 'fr' => 'Mobile (600 Pixel par défaut)'),
				'-no-background-tablet' => array('en' => 'Tablet (900 Pixel)', 'de' => 'Tablet (900 Pixel)', 'fr' => 'Tablette (900 Pixel par défaut)'),
            ),
			'eval' => array(
				'tl_class' => 'w50 clr',
				'includeBlankOption' => true,
			),
		),
		array(
			'inputType' => 'group',
			'label' => array(
				'en' => array('Height and alignment'),
				'de' => array('Höhe und Ausrichtung'),
                'fr' => array('Hauteur et alignement'),
            ),
		),
        'alignmentWrapper' => array(
            'label' => array(
                'en' => array('Wrapper Center horizontally', 'Change horizontal align.'),
                'de' => array('Wrapper Horizontal zentrieren', 'Horizontale Ausrichtung.'),
                'fr' => array('Wrapper Centrer horizontalement', 'Modifier l\'alignement horizontal'),
            ),
            'inputType' => 'select',
            'options' => array(
                '',
                'mx-auto',
            ),
            'reference' => array(
                '' => array('en' => 'Disable', 'de' => 'Disable', 'fr' => 'Désactivé'),
                'mx-auto' => array('en' => 'Centered', 'de' => 'Zentriert', 'fr' => 'Centré'),
            ),
            'eval' => array(
                'tl_class' => 'w50',
            ),
        ),
        'alignment' => array(
            'label' => array(
                'en' => array('Inner Wrapper Center horizontally', 'Change horizontal align and margin to side.'),
                'de' => array('Inner Wrapper Horizontal zentrieren', 'Horizontale Ausrichtung und Abstand zum Rand ändern.'),
                'fr' => array('Inner Wrapper Centrer horizontalement', 'Modifier l\'alignement horizontal et la marge sur le côté.'),
            ),
            'inputType' => 'select',
            'options' => array(
                '',
                '-fullwidth',
                '-fullwidth-padded',
            ),
            'reference' => array(
                '' => array('en' => 'Centered', 'de' => 'Zentriert', 'fr' => 'Centré'),
                '-fullwidth' => array('en' => 'Fullwidth without margin', 'de' => 'Fullwidth ohne Abstand', 'fr' => 'Pleine largeur sans marge'),
                '-fullwidth-padded' => array('en' => 'Fullwidth with margin', 'de' => 'Fullwidth mit Abstand', 'fr' => 'Pleine largeur avec marges'),
            ),
            'eval' => array(
                'tl_class' => 'w50',
            ),
        ),
		'verticalCentered' => array(
			'label' => array(
				'en' => array('Center vertically', 'Center content vertically.'),
				'de' => array('Vertikal zentrieren', 'Inhalt vertikal zentrieren.'),
                'fr' => array('Centrer verticalement', 'Centrer le contenu verticalement.'),
            ),
			'inputType' => 'checkbox',
			'eval' => array(
				'tl_class' => 'w50 m12',
			),
		),
        'width' => array(
            'label' => array(
                'en' => array('Force maximum width', 'Set the minimum height of the area to one of the values defined in the CSS.'),
                'fr' => array('Forcer la largeur', 'Définissez la largeur maximale de la zone sur l\'une des valeurs définies dans le CSS.'),
            ),
            'inputType' => 'select',
            'options' => array(
                '',
                'max-mobileportrait',
                'max-mobile',
                'max-tablet',
                'max-desktop',
                'max-desktopxl',
            ),
            'reference' => array(
                '' => array('en' => '-', 'de' => '-', 'fr' => '-'),
                'max-mobileportrait' => array('en' => 'Mobile portrait', 'de' => 'Mobile portrait', 'fr' => 'Mobile portrait'),
                'max-mobile' => array('en' => 'Mobile', 'de' => 'Mobile ', 'fr' => 'Mobile'),
                'max-tablet' => array('en' => 'Tablet', 'de' => 'Tablet ', 'fr' => 'Tablet'),
                'max-desktop' => array('en' => 'Desktop', 'de' => 'Desktop ', 'fr' => 'Desktop'),
                'max-desktopxl' => array('en' => 'DesktopXl', 'de' => 'DesktopXl ', 'fr' => 'DesktopXl'),
            ),
            'eval' => array('tl_class' => 'w50 clr'),
        ),
        'widthCustom' => array(
            'label' => array(
                'en' => array('Force maximum custom width', 'Set the minimum height of the area to one of the values defined in the CSS. ex: 500px'),
                'fr' => array('Forcer la largeur largeur selon une valeur définie manuellement', 'Définissez la largeur maximale de la zone. ex: 500px'),
            ),
            'inputType' => 'text',
            'eval' => array('tl_class' => 'w50'),
        ),
		'height' => array(
			'label' => array(
				'en' => array('Force minimum height', 'Set the minimum height of the area to one of the values defined in the CSS.'),
				'de' => array('Mindesthöhe erzwingen', 'Setzt die Mindesthöhe des Bereiches auf einen der im CSS definierten Werte.'),
                'fr' => array('Forcer la hauteur minimale', 'Définissez la hauteur minimale de la zone sur l\'une des valeurs définies dans le CSS.'),
            ),
			'inputType' => 'select',
			'options' => array(
				'',
				'-height-50',
				'-height-100',
				'-height-150',
				'-height-200',
				'-height-250',
				'-height-300',
				'-height-350',
				'-height-400',
				'-height-450',
				'-height-500',
				'-height-550',
				'-height-600',
				'-height-650',
				'-height-700',
				'-height-750',
				'-height-800',
				'-height-850',
				'-height-900',
				'-height-100percent',
				'-viewport-height',
			),
			'reference' => array(
				'' => array('en' => '-', 'de' => '-', 'fr' => '-'),
				'-height-50' => array('en' => '50px', 'de' => '50px', 'fr' => '50px'),
				'-height-100' => array('en' => '100px', 'de' => '100px', 'fr' => '100px'),
				'-height-150' => array('en' => '150px', 'de' => '150px', 'fr' => '150px'),
				'-height-200' => array('en' => '200px', 'de' => '200px', 'fr' => '200px'),
				'-height-250' => array('en' => '250px', 'de' => '250px', 'fr' => '250px'),
				'-height-300' => array('en' => '300px', 'de' => '300px', 'fr' => '300px'),
				'-height-350' => array('en' => '350px', 'de' => '350px', 'fr' => '350px'),
				'-height-400' => array('en' => '400px', 'de' => '400px', 'fr' => '400px'),
				'-height-450' => array('en' => '450px', 'de' => '450px', 'fr' => '450px'),
				'-height-500' => array('en' => '500px', 'de' => '500px', 'fr' => '500px'),
				'-height-550' => array('en' => '550px', 'de' => '550px', 'fr' => '550px'),
				'-height-600' => array('en' => '600px', 'de' => '600px', 'fr' => '600px'),
				'-height-650' => array('en' => '650px', 'de' => '650px', 'fr' => '650px'),
				'-height-700' => array('en' => '700px', 'de' => '700px', 'fr' => '700px'),
				'-height-750' => array('en' => '750px', 'de' => '750px', 'fr' => '750px'),
				'-height-800' => array('en' => '800px', 'de' => '800px', 'fr' => '800px'),
				'-height-850' => array('en' => '850px', 'de' => '850px', 'fr' => '850px'),
				'-height-900' => array('en' => '900px', 'de' => '900px', 'fr' => '900px'),
				'-height-100percent' => array('en' => '100%', 'de' => '100%', 'fr' => '100%'),
				'-viewport-height' => array('en' => 'Viewport', 'de' => 'Fensterhöhe', 'fr' => 'Hauteur du Viewport'),
			),
			'eval' => array('tl_class' => 'w50 clr'),
		),
        'heightMobile' => array(
            'label' => array(
                'en' => array('Force height Mobile', 'Set height of the area to one of the values defined in the CSS.'),
                'de' => array('Erzwingen Mobile', 'Setzt des Bereiches auf einen der im CSS definierten Werte.'),
                'fr' => array('Forcer la hauteur Mobile', 'Définissez la hauteur de la zone sur l\'une des valeurs définies dans le CSS.'),
            ),
            'inputType' => 'select',
            'options' => array(
                '',
                '-height-mobile-auto',
                '-height-mobile-50',
                '-height-mobile-100',
                '-height-mobile-150',
                '-height-mobile-200',
                '-height-mobile-250',
                '-height-mobile-300',
                '-height-mobile-350',
                '-height-mobile-400',
                '-height-mobile-450',
                '-height-mobile-500',
                '-height-mobile-550',
                '-height-mobile-600',
                '-height-mobile-650',
                '-height-mobile-700',
                '-height-mobile-750',
                '-height-mobile-800',
                '-height-mobile-850',
                '-height-mobile-900',
                '-height-mobile-100percent',
                '-viewport-height-mobile',
            ),
            'reference' => array(
                '' => array('en' => '-', 'de' => '-', 'fr' => '-'),
                '-height-mobile-auto' => array('en' => 'auto', 'de' => 'auto', 'fr' => 'auto'),
                '-height-mobile-50' => array('en' => '50px', 'de' => '50px', 'fr' => '50px'),
                '-height-mobile-100' => array('en' => '100px', 'de' => '100px', 'fr' => '100px'),
                '-height-mobile-150' => array('en' => '150px', 'de' => '150px', 'fr' => '150px'),
                '-height-mobile-200' => array('en' => '200px', 'de' => '200px', 'fr' => '200px'),
                '-height-mobile-250' => array('en' => '250px', 'de' => '250px', 'fr' => '250px'),
                '-height-mobile-300' => array('en' => '300px', 'de' => '300px', 'fr' => '300px'),
                '-height-mobile-350' => array('en' => '350px', 'de' => '350px', 'fr' => '350px'),
                '-height-mobile-400' => array('en' => '400px', 'de' => '400px', 'fr' => '400px'),
                '-height-mobile-450' => array('en' => '450px', 'de' => '450px', 'fr' => '450px'),
                '-height-mobile-500' => array('en' => '500px', 'de' => '500px', 'fr' => '500px'),
                '-height-mobile-550' => array('en' => '550px', 'de' => '550px', 'fr' => '550px'),
                '-height-mobile-600' => array('en' => '600px', 'de' => '600px', 'fr' => '600px'),
                '-height-mobile-650' => array('en' => '650px', 'de' => '650px', 'fr' => '650px'),
                '-height-mobile-700' => array('en' => '700px', 'de' => '700px', 'fr' => '700px'),
                '-height-mobile-750' => array('en' => '750px', 'de' => '750px', 'fr' => '750px'),
                '-height-mobile-800' => array('en' => '800px', 'de' => '800px', 'fr' => '800px'),
                '-height-mobile-850' => array('en' => '850px', 'de' => '850px', 'fr' => '850px'),
                '-height-mobile-900' => array('en' => '900px', 'de' => '900px', 'fr' => '900px'),
                '-height-mobile-100percent' => array('en' => '100%', 'de' => '100%', 'fr' => '100%'),
                '-viewport-height-mobile' => array('en' => 'Viewport', 'de' => 'Fensterhöhe', 'fr' => 'Hauteur du Viewport'),
            ),
            'eval' => array('tl_class' => 'w50 clr'),
        ),
        'maxHeightMobile' => array(
            'label' => array(
                'en' => array('Maximum height for mobile', 'Examples: 300px, 100vh'),
                'de' => array('Maximale Höhe für Handy', 'Beispiele: 300px, 100vh'),
                'fr' => array('Hauteur maximum pour mobile', 'Exemples: 300px, 100vh'),
            ),
            'inputType' => 'select',
            'options' => array(
                '',
                '-max-height-mobile-none',
                '-max-height-mobile-50',
                '-max-height-mobile-100',
                '-max-height-mobile-150',
                '-max-height-mobile-200',
                '-max-height-mobile-250',
                '-max-height-mobile-300',
                '-max-height-mobile-350',
                '-max-height-mobile-400',
                '-max-height-mobile-450',
                '-max-height-mobile-500',
                '-max-height-mobile-550',
                '-max-height-mobile-600',
                '-max-height-mobile-650',
                '-max-height-mobile-700',
                '-max-height-mobile-750',
                '-max-height-mobile-800',
                '-max-height-mobile-850',
                '-max-height-mobile-900',
                '-max-height-mobile-100percent',
                '-max-viewport-mobile-height',
            ),
            'reference' => array(
                '' => array('en' => '-', 'de' => '-', 'fr' => '-'),
                '-max-height-mobile-none' => array('en' => 'none', 'de' => 'none', 'fr' => 'none'),
                '-max-height-mobile-50' => array('en' => '50px', 'de' => '50px', 'fr' => '50px'),
                '-max-height-mobile-100' => array('en' => '100px', 'de' => '100px', 'fr' => '100px'),
                '-max-height-mobile-150' => array('en' => '150px', 'de' => '150px', 'fr' => '150px'),
                '-max-height-mobile-200' => array('en' => '200px', 'de' => '200px', 'fr' => '200px'),
                '-max-height-mobile-250' => array('en' => '250px', 'de' => '250px', 'fr' => '250px'),
                '-max-height-mobile-300' => array('en' => '300px', 'de' => '300px', 'fr' => '300px'),
                '-max-height-mobile-350' => array('en' => '350px', 'de' => '350px', 'fr' => '350px'),
                '-max-height-mobile-400' => array('en' => '400px', 'de' => '400px', 'fr' => '400px'),
                '-max-height-mobile-450' => array('en' => '450px', 'de' => '450px', 'fr' => '450px'),
                '-max-height-mobile-500' => array('en' => '500px', 'de' => '500px', 'fr' => '500px'),
                '-max-height-mobile-550' => array('en' => '550px', 'de' => '550px', 'fr' => '550px'),
                '-max-height-mobile-600' => array('en' => '600px', 'de' => '600px', 'fr' => '600px'),
                '-max-height-mobile-650' => array('en' => '650px', 'de' => '650px', 'fr' => '650px'),
                '-max-height-mobile-700' => array('en' => '700px', 'de' => '700px', 'fr' => '700px'),
                '-max-height-mobile-750' => array('en' => '750px', 'de' => '750px', 'fr' => '750px'),
                '-max-height-mobile-800' => array('en' => '800px', 'de' => '800px', 'fr' => '800px'),
                '-max-height-mobile-850' => array('en' => '850px', 'de' => '850px', 'fr' => '850px'),
                '-max-height-mobile-900' => array('en' => '900px', 'de' => '900px', 'fr' => '900px'),
                '-max-height-mobile-100percent' => array('en' => '100%', 'de' => '100%', 'fr' => '100%'),
                '-max-viewport-mobile-height' => array('en' => 'Viewport', 'de' => 'Fensterhöhe', 'fr' => 'Hauteur du Viewport'),
            ),
            'eval' => array('tl_class' => 'w50 clr'),
        ),
        'minHeightMobile' => array(
            'label' => array(
                'en' => array('Minimum height for mobile', 'Examples: 300px, 100vh'),
                'de' => array('Minimum Höhe für Handy', 'Beispiele: 300px, 100vh'),
                'fr' => array('Hauteur minimum pour mobile', 'Exemples: 300px, 100vh'),
            ),
            'inputType' => 'select',
            'options' => array(
                '',
                '-min-height-mobile-auto',
                '-min-height-mobile-50',
                '-min-height-mobile-100',
                '-min-height-mobile-150',
                '-min-height-mobile-200',
                '-min-height-mobile-250',
                '-min-height-mobile-300',
                '-min-height-mobile-350',
                '-min-height-mobile-400',
                '-min-height-mobile-450',
                '-min-height-mobile-500',
                '-min-height-mobile-550',
                '-min-height-mobile-600',
                '-min-height-mobile-650',
                '-min-height-mobile-700',
                '-min-height-mobile-750',
                '-min-height-mobile-800',
                '-min-height-mobile-850',
                '-min-height-mobile-900',
                '-min-height-mobile-100percent',
                '-min-viewport-mobile-height',
            ),
            'reference' => array(
                '' => array('en' => '-', 'de' => '-', 'fr' => '-'),
                '-min-height-mobile-auto' => array('en' => 'auto', 'de' => 'auto', 'fr' => 'auto'),
                '-min-height-mobile-50' => array('en' => '50px', 'de' => '50px', 'fr' => '50px'),
                '-min-height-mobile-100' => array('en' => '100px', 'de' => '100px', 'fr' => '100px'),
                '-min-height-mobile-150' => array('en' => '150px', 'de' => '150px', 'fr' => '150px'),
                '-min-height-mobile-200' => array('en' => '200px', 'de' => '200px', 'fr' => '200px'),
                '-min-height-mobile-250' => array('en' => '250px', 'de' => '250px', 'fr' => '250px'),
                '-min-height-mobile-300' => array('en' => '300px', 'de' => '300px', 'fr' => '300px'),
                '-min-height-mobile-350' => array('en' => '350px', 'de' => '350px', 'fr' => '350px'),
                '-min-height-mobile-400' => array('en' => '400px', 'de' => '400px', 'fr' => '400px'),
                '-min-height-mobile-450' => array('en' => '450px', 'de' => '450px', 'fr' => '450px'),
                '-min-height-mobile-500' => array('en' => '500px', 'de' => '500px', 'fr' => '500px'),
                '-min-height-mobile-550' => array('en' => '550px', 'de' => '550px', 'fr' => '550px'),
                '-min-height-mobile-600' => array('en' => '600px', 'de' => '600px', 'fr' => '600px'),
                '-min-height-mobile-650' => array('en' => '650px', 'de' => '650px', 'fr' => '650px'),
                '-min-height-mobile-700' => array('en' => '700px', 'de' => '700px', 'fr' => '700px'),
                '-min-height-mobile-750' => array('en' => '750px', 'de' => '750px', 'fr' => '750px'),
                '-min-height-mobile-800' => array('en' => '800px', 'de' => '800px', 'fr' => '800px'),
                '-min-height-mobile-850' => array('en' => '850px', 'de' => '850px', 'fr' => '850px'),
                '-min-height-mobile-900' => array('en' => '900px', 'de' => '900px', 'fr' => '900px'),
                '-min-height-mobile-100percent' => array('en' => '100%', 'de' => '100%', 'fr' => '100%'),
                '-min-viewport-mobile-height' => array('en' => 'Viewport', 'de' => 'Fensterhöhe', 'fr' => 'Hauteur du Viewport'),
            ),
            'eval' => array('tl_class' => 'w50 clr'),
        ),
		array(
			'inputType' => 'group',
			'label' => array(
				'en' => array('Animation & Effects'),
				'de' => array('Animation & Effkte'),
                'fr' => array('Animations et effets'),
            ),
		),
		'fadeIn' => array(
			'label' => array(
				'en' => array('Activate fade-in effect', 'Fades the area in as soon as it\'s visible.'),
				'de' => array('Einblendeffekt aktivieren', 'Blendet den Bereich ein, sobald er ins Sichtfenster kommt.'),
                'fr' => array('Activer l\'effet de fondu', 'Estompe la zone dès qu\'elle est visible.'),
            ),
			'inputType' => 'checkbox',
			'eval' => array(
				'tl_class' => 'w50 m12',
			),
		),
		'doesRepeat' => array(
			'label' => array(
				'en' => array('Repeat effect', 'Repeats the effect every time the area comes into view again.'),
				'de' => array('Effekt wiederholen', 'Wiederholt der Effekt, sobald der Bereich erneut ins Sichtfenster kommt.'),
                'fr' => array('Effet de répétition', 'Répète l\'effet à chaque fois que la zone apparaît à nouveau.'),
            ),
			'inputType' => 'checkbox',
			'eval' => array(
				'tl_class' => 'w50 m12',
			),
		),
	),
);
